# ============================================================
# SALES PERFORMANCE & BUSINESS INTELLIGENCE ANALYSIS
# ============================================================

# Objective:
# Analyze sales data to identify sales trends, product performance,
# regional performance, customer behavior, and shipping performance.
# The analysis is used to generate meaningful business insights
# for the Power BI dashboard.


# ============================================================
# 1. IMPORTING LIBRARIES
# ============================================================

import pandas as pd


# ============================================================
# 2. LOADING THE DATASET
# ============================================================

# Load the Superstore sales dataset
df = pd.read_csv(r"C:\Users\91783\OneDrive\Desktop\superstore.csv")


# ============================================================
# 3. DATA PREPROCESSING
# ============================================================

# Convert Order Date and Ship Date columns from text to datetime
# so that date-based analysis can be performed.
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)
df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst=True)


# ============================================================
# 4. DATA INSPECTION & DATA QUALITY ASSESSMENT
# ============================================================

# Check the number of rows and columns in the dataset
print("Dataset Shape:", df.shape)

# Check for missing values in each column
print("\nMissing Values:")
print(df.isnull().sum())

# Check for duplicate records
print("\nDuplicate Rows:", df.duplicated().sum())

# Check the time period covered by the dataset
print("\nDate Range:")
print("Start:", df['Order Date'].min().strftime('%d/%m/%Y'))
print("End:", df['Order Date'].max().strftime('%d/%m/%Y'))


# ============================================================
# 5. SALES STATISTICS
# ============================================================

# Generate descriptive statistics for the Sales column
print("\nSales Statistics:")
print(df['Sales'].describe())

# Calculate total sales generated during the period
print("\nTotal Sales:")
print(f"{df['Sales'].sum():,.2f}")


# ============================================================
# 6. SALES BY CATEGORY
# ============================================================

# Identify which product category generates the highest sales
print("\nSales by Category:")
print(
    df.groupby('Category')['Sales']
      .sum()
      .sort_values(ascending=False)
      .round(2)
)


# ============================================================
# 7. SALES BY SUB-CATEGORY
# ============================================================

# Identify the highest-selling product sub-categories
print("\nSales by Sub-Category:")
print(
    df.groupby('Sub-Category')['Sales']
      .sum()
      .sort_values(ascending=False)
      .round(2)
)


# ============================================================
# 8. SALES BY REGION
# ============================================================

# Compare sales performance across different regions
print("\nSales by Region:")
print(
    df.groupby('Region')['Sales']
      .sum()
      .sort_values(ascending=False)
      .round(2)
)


# ============================================================
# 9. YEARLY SALES TREND
# ============================================================

# Calculate total sales for each year
print("\nYearly Sales:")
print(
    df.groupby(df['Order Date'].dt.year)['Sales']
      .sum()
      .round(2)
)


# ============================================================
# 10. MONTHLY SALES TREND
# ============================================================

# Calculate monthly sales to identify changes in sales over time
print("\nMonthly Sales:")
print(
    df.groupby(df['Order Date'].dt.to_period('M'))['Sales']
      .sum()
      .round(2)
)


# ============================================================
# 11. SALES BY CUSTOMER SEGMENT
# ============================================================

# Compare sales generated by different customer segments
print("\nSales by Segment:")
print(
    df.groupby('Segment')['Sales']
      .sum()
      .sort_values(ascending=False)
      .round(2)
)


# ============================================================
# 12. TOP 10 CUSTOMERS BY SALES
# ============================================================

# Identify the customers who generated the highest total sales
print("\nTop 10 Customers by Sales:")
print(
    df.groupby('Customer Name')['Sales']
      .sum()
      .sort_values(ascending=False)
      .head(10)
      .round(2)
)


# ============================================================
# 13. TOP 10 PRODUCTS BY SALES
# ============================================================

# Identify the products with the highest total sales
print("\nTop 10 Products by Sales:")
print(
    df.groupby('Product Name')['Sales']
      .sum()
      .sort_values(ascending=False)
      .head(10)
      .round(2)
)


# ============================================================
# 14. SHIPPING PERFORMANCE
# ============================================================

# Calculate the number of days between order date and ship date
df['Shipping Days'] = (
    df['Ship Date'] - df['Order Date']
).dt.days

# Generate statistics for shipping duration
print("\nShipping Days Statistics:")
print(df['Shipping Days'].describe().round(2))


# ============================================================
# 15. SHIPPING PERFORMANCE BY SHIP MODE
# ============================================================

# Compare the average shipping duration for each shipping mode
print("\nAverage Shipping Days by Ship Mode:")
print(
    df.groupby('Ship Mode')['Shipping Days']
      .mean()
      .sort_values()
      .round(2)
)


# ============================================================
# 16. ORDER & CUSTOMER SUMMARY
# ============================================================

# Calculate the number of unique orders and customers
print("\nOrder and Customer Summary:")

print("Unique Orders:", df['Order ID'].nunique())

print("Unique Customers:", df['Customer ID'].nunique())

# Calculate average sales value per order
average_sales_per_order = (
    df.groupby('Order ID')['Sales']
      .sum()
      .mean()
)

print("Average Sales per Order:", round(average_sales_per_order, 2))

























































































